services:
  - type: web
    name: my-python-backend
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
